chore

diff --git a/.github/pre_commit/pre-commit b/.github/pre_commit/pre-commit
--- a/.github/pre_commit/pre-commit
+++ b/.github/pre_commit/pre-commit
@@ -1,10 +1,34 @@
 #!/bin/sh
 STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")
 
-if [[ "$STAGED_GO_FILES" = "" ]]; then
+if [ "$STAGED_GO_FILES" = "" ]; then
     echo "no go files were stashed"
     exit 0
 fi
 
 echo "found some interesting files!"
-exit 1
+
+PASS=true
+
+for FILE in $STAGED_GO_FILES
+do
+    goimports -w $FILE
+
+    go vet $FILE
+    if [[ $? != 0]]; then
+        PASS=false
+    fi
+
+    golint "-set_exit_status" $FILE
+    if [[ $? == 1 ]]; then
+        PASS=false
+    fi
+done
+
+if ! PASS; then
+    printf "COMMIT FAILED\n"
+    exit 1
+else
+    printf "COMMIT SUCCEEDED\n"
+fi
+exit 0
