chore

diff --git a/.github/pre_commit/pre-commit b/.github/pre_commit/pre-commit
--- a/.github/pre_commit/pre-commit
+++ b/.github/pre_commit/pre-commit
@@ -2,11 +2,8 @@
 STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")
 
 if [ "$STAGED_GO_FILES" = "" ]; then
-    echo "no go files were stashed"
     exit 0
 fi
-
-echo "found some interesting files!"
 
 PASS=true
 
@@ -18,17 +15,13 @@ do
     if [[ $? != 0]]; then
         PASS=false
     fi
-
-    golint "-set_exit_status" $FILE
-    if [[ $? == 1 ]]; then
-        PASS=false
-    fi
+    
 done
 
-if ! PASS; then
-    printf "COMMIT FAILED\n"
-    exit 1
+if ! $PASS; then
+  printf "\033[0;30m\033[41mCOMMIT FAILED\033[0m\n"
+  exit 1
 else
-    printf "COMMIT SUCCEEDED\n"
+  printf "\033[0;30m\033[42mCOMMIT SUCCEEDED\033[0m\n"
 fi
 exit 0
